-- +goose Up
-- +goose StatementBegin
create extension if not exists citext;

create table goods(
    id bigint primary key generated by default as identity,
    brand citext not null,
    place_save citext not null,
    store_house int not null,
    worker citext not null,
    inserted_at timestamp(0) not null default (now() at time zone 'utc'),
    update_at timestamp(0) not null default (now() at time zone 'utc')

);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table goods;
-- +goose StatementEnd
